# Generated by Django 4.0.5 on 2022-08-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0011_gst_tds_person_remove_person_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gst',
            name='app_from',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gst',
            name='billfrom_place',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gst',
            name='dperiod',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gst',
            name='send_ewaybill',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
