import email
from django.db import models

# Create your models here.
class Companies(models.Model):
    name=models.CharField(max_length=225)
    mailing_name=models.CharField(max_length=225)
    address=models.TextField()
    pincode=models.CharField(max_length=6)
    telephone=models.CharField(max_length=225)
    mobile=models.CharField(max_length=225)
    fax=models.CharField(max_length=225)
    email=models.EmailField()
    website=models.CharField(max_length=225)
    fin_begin=models.DateField(null=True)
    books_begin=models.DateField(null=True)
    state=models.CharField(max_length=225,default=True)
    country=models.CharField(max_length=225,default=True)
    currency_symbol=models.CharField(max_length=225)
    formal_name=models.CharField(max_length=225)
    fin_end=models.DateField(null=True)
    status=models.BooleanField(default=False)
class GST(models.Model):
    state = models.CharField(max_length=225)
    reg_type= models.CharField(max_length=225)
    assessee= models.CharField(max_length=225)
    gst_applicable= models.CharField(max_length=225)
    gstin= models.CharField(max_length=225)
    periodicity= models.CharField(max_length=225)
    gst_rate_details= models.CharField(max_length=225)
    advance_receipts= models.CharField(max_length=225)
    reverse_charge= models.CharField(max_length=225)
    gst_classification= models.CharField(max_length=225)
    bond_details= models.CharField(max_length=225)
    eway_bill= models.CharField(max_length=225)
    applicable_form= models.CharField(max_length=225)
    threshold_includes= models.CharField(max_length=225)
    threshold_limit= models.CharField(max_length=225)
    intrastate= models.CharField(max_length=225)
    threshold_limit2= models.CharField(max_length=225)
    print_eway= models.CharField(max_length=225)
    e_invoice= models.CharField(max_length=225)
    app_from=models.CharField(max_length=255,null=True)
    billfrom_place=models.CharField(max_length=255,null=True)
    dperiod=models.CharField(max_length=255,null=True)
    send_ewaybill=models.CharField(max_length=255,null=True)
    
    company=models.ForeignKey(Companies,on_delete=models.CASCADE,blank=True,null=True)
    
class Tds_Details(models.Model):
    tan_regno=models.CharField(max_length=255)
    tan=models.CharField(max_length=255)
    deductor_type=models.CharField(max_length=255)
    deductor_branch=models.CharField(max_length=255)
    person_details=models.CharField(max_length=255)
    ignore_it=models.CharField(max_length=255)
    active_tds=models.CharField(max_length=255)
    company=models.ForeignKey(Companies,on_delete=models.CASCADE,blank=True,null=True)
    
class tds_person(models.Model):
    name=models.CharField(max_length=255)
    son_daughter=models.CharField(max_length=255)
    designation=models.CharField(max_length=255)
    pan=models.CharField(max_length=255)
    flat_no=models.CharField(max_length=255)
    building=models.CharField(max_length=255)
    street=models.CharField(max_length=255)
    area=models.CharField(max_length=255)
    town=models.CharField(max_length=255)
    state=models.CharField(max_length=255)
    pincode=models.CharField(max_length=255)
    mobile=models.CharField(max_length=255)
    std=models.CharField(max_length=255)
    telephone=models.CharField(max_length=255)
    email=models.CharField(max_length=255)
    company=models.ForeignKey(Companies,on_delete=models.CASCADE,blank=True,null=True)
    
class Features(models.Model):
    maintain_accounts = models.CharField(max_length=255)
    bill_wise_entry =  models.CharField(max_length=255)
    cost_centres =  models.CharField(max_length=255)
    interest_calc =  models.CharField(max_length=255)
    maintain_inventory =  models.CharField(max_length=255)
    integrate_accounts =  models.CharField(max_length=255)
    multiple_price_level =  models.CharField(max_length=255)
    batches =  models.CharField(max_length=255)
    expirydate_batches =  models.CharField(max_length=255)
    joborder_processing =  models.CharField(max_length=255)
    cost_tracking=  models.CharField(max_length=255)
    job_costing =  models.CharField(max_length=255)
    discount_invoices = models.CharField(max_length=255)
    Billed_Quantity =  models.CharField(max_length=255)
    gst =  models.CharField(max_length=255)
    tds =  models.CharField(max_length=255)
    tcs =  models.CharField(max_length=255)
    vat =  models.CharField(max_length=255)
    excise =  models.CharField(max_length=255)
    servicetax =  models.CharField(max_length=255)
    payroll =  models.CharField(max_length=255)
    # payroll_statutory= models.CharField(max_length=255)
    multiple_addrss =  models.CharField(max_length=255)
    vouchers =  models.CharField(max_length=255)
    
    company=models.ForeignKey(Companies,on_delete=models.CASCADE,blank=True,null=True)
    
class Countries(models.Model):
    name=models.CharField(max_length=225)
    
class States(models.Model):
    name=models.CharField(max_length=225)
    country=models.ForeignKey(Countries,on_delete=models.CASCADE,blank=True,null=True)
    